### ISSUE TITLE
CP Socket fix

### ISSUE THREAD

**Issue by Doomject-Supreme** [skyslide22/blendermania-addon#19]
Dear author, when creating a CP a socket is required. By default a  mesh of the TM car will be spawned. This causes the item to not export. The _socket_ needs to be an object of the type "empty". Could you please fix this issue, by replacing the car with an empty object? There is no mention in the wiki as well, that the object has to be "empty".

Thanks for the awesome work.

**Comment by skyslide22** [comment]
please talk about this with florenzius on the trackmania scenery discord, he is in contact with nadeo and can forward this issue, if not already done.

**Comment by skyslide22** [comment]
fixed with 3.0 which will be released in the next days
