### ISSUE TITLE
Trouble Exporting + one question

### ISSUE THREAD

**Issue by Medatur76** [skyslide22/blendermania-addon#28]
Hello! I am new to gbx and have almost no history with python so I can't make sense of a couple of different errors I get when exporting.
The first is when I export NadeoImporter cant find the Item.xml file. I did look into the docs so I know it is required and the addon should export it. Yesterday the addon was working just fine and after converting the fbx to gbx the fbx, Item.xml, and MeshParams.xml were left over but today after exporting I can't find any of those files. The second problem I encounter I'm not sure if it's a blender issue or a plugin issue but after trying to export blender crashes without any error log window, just closes. There is another error which I remember ends with ""EDIT" not id object..." I'm pretty sure but I can't reproduce it. I have looked at the docs and done what it told me to do but I still can't get it to work. This last part isn't involving the errors but as I mentioned I could export objects yesterday and when in the editor half the object was underground and before placing the object I could only see parts of it. What I mean is the object(a building to be specific) was made up of multiple cubes, I could see them after placement but I couldn't before. If anyone can help me with my two issues I would greatly appreciate it. Thanks in advance! Let me know if you need anything else to help in fixing the issue! :)

**Comment by skyslide22** [comment]
ay Medatur76, please give us more information by providing the exact error messages.

You can do that by running blender from the terminal. do <kbd>win + r</kbd> then type `cmd`.
Now write in the terminal: `cd c:\<blender installation directory> blender` (you need to write down your blender directory)
If blender crashes you get all the stuff you need in the terminal/command-line.

Also, the nadeo.ini file should be selected, that file has the information where your trackmania files are stores (ususally documents/trackmania/...

Gbx files are created in the items folder, the fbx and xml files are in work/items, this is mandatory.

**Comment by Medatur76** [comment]
I know that I need the nadeo.ini but the problem is the item.xml and meshparams.xml are not created. Here is the message for that error: "Item.xml not found, does it exists?" and the log: "Convert steps until convert failed:
Collection: Start convert to game Trackmania2020
Collection: Convert .fbx to .Item.gbx
Collection: Command: "C:/Program Files (x86)/Steam/steamapps/common/Trackmania/NadeoImporter.exe" Item "Items/Collection.Item.xml"
Collection: Convert to .Item.gbx failed
Collection: Convert failed
item returncode: 1
item error msg: NadeoImporter 2022-07-12_17_05 File not found in '{userdir}/Work/': Items\Collection.Item.xml"
Today I am unable to reproduce the crash error but if I give blender administrator I get the error above, if I don't it says permission denied

**Comment by Medatur76** [comment]
After a little bit of testing, I found that instead of sending the export files to
`C:\Users\{User}\Documents\Trackmania\Work\Items`
the files were being exported to
`C:\Trackmania\Work\Items`
How do I fix this and the half-above error from earlier?

**Comment by Medatur76** [comment]
Nevermind, I fixed the export error, for any curious here was the fix: When choosing a folder the plugin put `/..\.\Trackmania\Work\Items` or something close to that so the fix was to manually put in the folder path. One last note I will experiment with that half-showing glitch and if I cant fix it I will open this up again.
