### ISSUE TITLE
TDSNI_Night materials don't work correctly

### ISSUE THREAD

**Issue by zai-tm** [skyslide22/blendermania-addon#32]
TDSNI_Night materials will fail on conversion, I think it might be the capitalization used

**Comment by zai-tm** [comment]
Update: It is infact the capitalization, the addon uses **TDSNI_NIGHT**, while the game is looking for **TDSNI_Night**

**Comment by skyslide22** [comment]
will be fixed in the next release https://github.com/skyslide22/blendermania-addon/commit/d2ee5fbbe49490280f8eeba7c04e6435cdbdb1a6
