### ISSUE TITLE
Meshes created by extruding vertex points always result in "LightMap TexCoord Invalid Surface"

### ISSUE THREAD

**Issue by SeraEris** [skyslide22/blendermania-addon#40]
Using any of the following workflows always results in items that cannot be converted due to UV issues, but cannot be corrected by regular blender manipulations such as resetting or re-projecting UV layouts.

1. Create a mesh from a single vertex point, instead of starting with a plane or cube.
2. Duplicate vertex points from an existing item, separating them into a different object, then extruding them into faces.

In the instances where I have a specific curve or line I want to extrude into a separate item, I am currently forced to create an entirely new mesh, subdivide it as needed, and merge-snap it's vertices into place.

I presume this has something to do with lacking an initial face to iterate upon or something, but the convert report fails to specify.

Adding a default flat plane or cube to a 'broken' mesh will still result in failure, indicating this is an issue with the 'first' face in the object data.

Additionally, re-applying the material to all faces by selecting them and assigning the material in edit mode did not resolve this.

Blender 4.0.2

`Item Code: 1 (error)`

`Mesh Code: 0 (success)`

`Conversion Log:`
`Start convert to game Trackmania2020`
`Convert .fbx => .Item.gbx`
`Command: "C:/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/games/Trackmania/NadeoImporter.exe"`
`Item "Items/FastLaneExport/Connector/Connector-Sides.Item.xml"`
`Convert to .Item.gbx failed`
`Convert failed`
`Returncode: 1`
`Original Response: NadeoImporter 2022-07-12_17_05`
`Failed to generate mesh for ":user:\Work\Items\FastLaneExport\Connector\Connector-Sides.fbx":`
`LightMap TexCoord Invalid Surface (might be 0)`

_And for posterity, on all 10 instances of encountering this issue, there were no invalid UVs or missed faces._
_This was verified by both ( separately ) resetting and reprojecting ( with both 'follow active quads' and 'project from view' )._

**Comment by skyslide22** [comment]
This is not a Blendermania issue but rather a problem with the `NadeoImporer.exe` which converts the exported fbx files to gbx files. Blendermania itself does not convert anything, it just generates the necessary files and provides/limits some features related to blender in context to Trackmania.

The problem you have is usually related to vertices at 0,0 in the `lightmap` uv layer, or 1 dimensional faces (faces which act like a line, or just a dot)

I would suggest to:
- make sure the mesh has no 1d faces
- check if the lightmap is unwrapped correctly(no overlaps, no 0/1 dimesional faces

Example Triangle which caused this issue sometimes for me:

```
Correct:
   .
  / \
./___\.
```

```
Corrupt (height missing):
.__.__.
```

**Comment by SeraEris** [comment]
These problems have been verified, please see initial comments in post about repo steps and tried solutions.

I ensured that there were no 1d faces in any of the 10 different meshes that resulted from either listed method in the repo steps.
I additionally ensured that the UV of all faces was either reset ( to the full 0,0 -> 1,1 square ), which did not work, or reprojecting, which also did not work.

**Comment by SeraEris** [comment]
![image](https://github.com/skyslide22/blendermania-addon/assets/8411750/9de4f666-c3f6-4b53-b260-91f3c2d70f33)

[UV-Fail-Example.zip](https://github.com/skyslide22/blendermania-addon/files/14657421/UV-Fail-Example.zip)

I've created a blend file with two default planes, one made by adding the blender prefab, the other by using method #2, and extruding a new plane with extrusion from a single edge. The UV is identical in both, and I have no means of resolving it.

**Comment by SeraEris** [comment]
After searching, I did find the lightmap UV you were referring to- Could you please add a screenshot of the UV layer selection to the feedback page when this issue is encountered?

![image](https://github.com/skyslide22/blendermania-addon/assets/8411750/00016646-aa96-4a47-a823-a198d9cebf24)

Also it would be phenomenal if you had an easy button or auto-resolve for this issue that would use the base material UV for the lightmap UV in case of failure.

**Comment by skyslide22** [comment]
The lightmap should not have overlaps, usinging the basematerial is not the idea solution on a failure.
You can do that yourself if you want, but lightmap will be corrupt – but the object will convert, for testing.
- by deleting the lightmap(-) and add a new uv layer (+) it copies the previous uv layer data
i will take a look on the example the next days.

**Comment by SeraEris** [comment]
The example I included has the failed lightmap UV in it, as you correctly pointed out.

Thanks for the tip on duplicating the UV layers, and the note about overlaps.

**Comment by skyslide22** [comment]
You can take a look at https://github.com/skyslide22/blendermania-addon/wiki/05.-UV-Maps for more info about the uv layers requirement for trackmania

**Comment by SeraEris** [comment]
If I'm importing the exported meshes into in-game created objects as separate layers, and not using the items exported as-is, does the blender lightmap UV matter?

**Comment by skyslide22** [comment]
The meshmodeler will overwrite the lightmap on save, so the lightmap generated with blender will be lost at that point.
If you want to mofify the item in-game you can ignore the quality of the lightmap, just get your object to convert – copying the basematerial will do the job in this case.

**Comment by SeraEris** [comment]
I guess that's what I was getting tripped up on, maybe a better formed request would be to expand the meshmodeler export option:
![image](https://github.com/skyslide22/blendermania-addon/assets/8411750/8390fe83-afdf-4d7f-9c8c-67d0307f9787)

Instead of just a toggle on to dump extras, it would be nice to only export these instead, and more often than not in my case, export the Mesh or Shape only.
